name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greetings
        run: echo "Hello World"
      - name: Middle Greetings
        run: echo "Hi Middle one"
      - name: Second Middle
        run: echo "second Middle one"
      - name: Print GoodBye
        run: echo "Done - Bye"
